admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
reference:
    resource: '@AcmeMyReferenceBundle/Resources/config/routing.yml'
    prefix: /reference
rest : 
    type : rest 
    resource : "routing_rest.yml"
    prefix : /api
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

# sonata_api_media:
#     type:         rest
#     prefix:       /api
#     resource:     "@SonataMediaBundle/Resources/config/routing/api.xml"
