parameters:
#    acme_my_reference.example.class: Acme\MyReferenceBundle\Example

services:
#    acme_my_reference.example:
#        class: %acme_my_reference.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
