services:
    sonata.admin.post:
        class: Acme\DemoBundle\Admin\PostAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "acme.admin.group.content"
              label: "acme.admin.model.post"
              label_catalogue: "AcmeDemoBundle"
        arguments:
            - ~
            - Acme\DemoBundle\Entity\Post
            - ~